### ISSUE TITLE
missing arch dependencies

### ISSUE THREAD

**Issue by tones111** [redox-os/libc#39]
The gcc PKGBUILD files have a dependency on an old version of autoconf.  It would be helpful to have PKGBUILDs for any dependencies that aren't available.

**Comment by ids1024** [comment]
That package used to be in the repositories, and is still available from https://archive.archlinux.org/packages/a/autoconf-2.64/autoconf-2.64-2.64-1-any.pkg.tar.xz

Perhaps merging upstream gcc into the Redox fork would make it work with a newer version?

Actually, Redox's gcc fork seems to have the relevant file committed, so it should be fine to just remove that call from the PKGBUILD...
