### ISSUE TITLE
Update GNU build tools

### ISSUE THREAD

**Issue by anxiousmodernman** [redox-os/libc#46]
I built redox and dependencies for the first time. My build environment was Arch Linux, and I didn't want to use docker. Some notes:

* older versions of aclocal and automake (which libc build and redox build use) [contain Perl code that will not run under the latest Perl](https://cygwin.com/ml/cygwin/2015-09/msg00344.html). This is due to the changes in Perl regular expressions syntax.
* the libc builds need autoconf-2.64 and automake-1.11, but redox needs automake-1.12; I built everything from source to get it right
* this is all my fault for using Arch, which does not maintain old versions of official packages 😢 

End-to-end builds would be easier if the versions of build tools were made to match across libc, newlib, and redox. Is there any reason we can't do this, in principle?

**Comment by jackpot51** [comment]
newlib keeps us stuck on automake 1.11 and autoconf 2.64.

Unless upstream updates their syntax, we are stuck

**Comment by anxiousmodernman** [comment]
But which syntax? If it's syntax in the build scripts themselves, like macros in configure.ac files, those can be updated (with some effort).

**Comment by anxiousmodernman** [comment]
I guess if we are going to keep pulling upstream, we are stuck.

**Comment by jackpot51** [comment]
Perhaps we could consider using another libc? I have not looked into others that deeply, but `glibc` would probably be good to port.

**Comment by BearzRobotics** [comment]
Would [musl](https://www.musl-libc.org/) be a good fit to port?

**Comment by anxiousmodernman** [comment]
So, musl is smaller (on purpose), so the first question would be whether it has the apis we need. I believe it does, since there are Rust projects that use musl for static compilation.

**Comment by BearzRobotics** [comment]
I know there are Linux distros based around it for example [Alpine](https://alpinelinux.org/), so it should have everything that would be needed for redox, but I could be wrong.

**Comment by dlrobertson** [comment]
+1 for musl. I use Gentoo with musl on a few boxes.

**Comment by jackpot51** [comment]
No, it is not. musl expects implementations for a very large range of Linux syscalls, and is not meant to be portable

**Comment by dralley** [comment]
Given that the long term solution will be relibc, I assume this issue can be closed.

**Comment by anxiousmodernman** [comment]
Agreed! Stoked about relibc.
