### ISSUE TITLE
NewLib ArchLinux package won't compile

### ISSUE THREAD

**Issue by eisterman** [redox-os/libc#50]
Following https://doc.redox-os.org/book/getting_started/installing_the_toolchain.html i've tried to compile the toolchain for Archlinux.
But the makepkg for newlib won't work.

This is the [log](https://gist.github.com/eisterman/d87b29d5f3d637f25c69d48c8e88b394) for `makepkg -si 2> log2.txt`. This is the third recompilation. 
There is this problem even with a new clone of the remote reporsitory.

The important part is:
```x86_64-unknown-redox-ar cru lib.a lib_a-sysclose.o lib_a-sysfcntl.o lib_a-sysfstat.o lib_a-sysgetpid.o lib_a-sysgettod.o lib_a-sysisatty.o lib_a-syskill.o lib_a-syslink.o lib_a-syslseek.o lib_a-sysopen.o lib_a-sysread.o lib_a-syssbrk.o lib_a-sysstat.o lib_a-systimes.o lib_a-sysunlink.o lib_a-syswrite.o lib_a-sysexecve.o lib_a-sysfork.o lib_a-syswait.o 
x86_64-unknown-redox-ranlib lib.a
make[5]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib/libc/syscalls'
Making all in .
make[5]: Entering directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib/libc'
rm -f libc.a
rm -f crt0.o
rm -rf tmp
ln sys/crt0.o crt0.o >/dev/null 2>/dev/null || cp sys/crt0.o crt0.o
mkdir tmp
cd tmp; \
 for i in argz/lib.a stdlib/lib.a ctype/lib.a search/lib.a stdio/lib.a   string/lib.a signal/lib.a time/lib.a locale/lib.a reent/lib.a  errno/lib.a misc/lib.a unix/lib.a posix/lib.a syscalls/lib.a  machine/lib.a sys/lib.a; do \
   x86_64-unknown-redox-ar x ../$i; \
 done; \
x86_64-unknown-redox-ar rc ../libc.a *.o
cp: cannot stat 'sys/crt0.o': No such file or directory
make[5]: *** [Makefile:1043: crt0.o] Error 1
make[5]: *** Waiting for unfinished jobs....
x86_64-unknown-redox-ar: ../sys/lib.a: No such file or directory
x86_64-unknown-redox-ranlib libc.a
rm -rf tmp
make[5]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib/libc'
make[4]: *** [Makefile:680: all-recursive] Error 1
make[4]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib/libc'
make[3]: *** [Makefile:642: all-recursive] Error 1
make[3]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib'
make[2]: *** [Makefile:453: all] Error 2
make[2]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build/x86_64-unknown-redox/newlib'
make[1]: *** [Makefile:8492: all-target-newlib] Error 2
make[1]: Leaving directory '/home/fpasqua/OperativeSystems/libc/packages/arch/newlib/src/newlib-build'
make: *** [Makefile:879: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by eisterman** [comment]
After a manual installation of all the tool required with the corrected version (and a special ./configure for autoconf for name collision, case not covered by setup.sh) i have a new error:
```make[1]: Leaving directory '/home/fpasqua/OperativeSystems/libc/build/cross/gcc-freestanding/x86_64-unknown-redox/libgcc'
~/OperativeSystems/libc/build/cross
Defaulting to rust nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: override toolchain for '/home/fpasqua/OperativeSystems/libc/build/cross' set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.25.0-nightly (27a046e93 2018-02-18)

Update rust nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.25.0-nightly (27a046e93 2018-02-18)

Downloading rust source
info: component 'rust-src' is up to date
~/OperativeSystems/libc/newlib/newlib/libc/sys ~/OperativeSystems/libc/build/cross
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal-1.11 line 622.
configure.in:20: warning: macro `AM_PROG_LIBTOOL' not found in library
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake-1.11 line 4153.
```

But, if the arch packages sometimes not work, why are in the _official_ documentation???

**Comment by sajattack** [comment]
The error you have now is due to a version mismatch between perl and automake. Install automake-1.11 from aur, it has the patch

**Comment by eisterman** [comment]
Problem solved.

I will create PR for the extension of the documentation

**Comment by aticu** [comment]
@eisterman Could you please elaborate on the steps you took to solve the issue? I'm running into the same problem.

**Comment by jeffvandyke** [comment]
I too am still having issues with the arch packages. `autoconf`, `gcc-freestanding`, and `binutils` all install fine, but `newlib` fails with pretty much the same error as OP. I'd really like to use these packages to avoid messing up my environment by manually installing autoconf-2.64 without the package (that's my issue with the setup.sh approach - without a guided PKGBUILD solution it requires automake to be version 2.64, and I do NOT want to have non-package-managed files in system directories)

I tried looking into it, but line 1043 of newlib/src/newlib-build/x86_64-unknown-redox/newlib/libc/Makefile seemed like it was assuming that sys/crt0.o was already present (the sys/crt0.o target was simply: `@true`), maybe it was supposed to be present from some non-specified dependency/side-effect, and I don't know enough about newlib to know where to look next, but I would like to get this repo building from a relatively clean dev environment using the packages/arch method. (Yes, I'm using rustup with nightly as default, just in case)

Any bright ideas for PKGBUILD fixes?

**Comment by eisterman** [comment]
I'm trying, but we need to know HOW sys/crt0.o is intended to be generated

**Comment by yanganto** [comment]
I have the same issue, if there is anything I can try, please tell me.

**Comment by stevenvandenbrandenstift** [comment]
i suppose this is a bad idea, but
//#[lang = "oom"]
//#[linkage = "weak"]
//#[no_mangle]
//pub extern fn rust_oom() -> ! {
//    panic!("memory allocation failed");
//}
makes my able to build newlib, so i suppose that the oom language feature is changed?

**Comment by stevenvandenbrandenstift** [comment]
its because an older rust compiler is used

**Comment by stevenvandenbrandenstift** [comment]
the solution is the update the rust compiler, shall we update the redox book, or fix the PKGBUILD to do this ?

**Comment by stevenvandenbrandenstift** [comment]
use version nightly-2018-04-27 in the Pkgbuild , like the one for setup.sh, will make a pull request after i verified its working ok

**Comment by stevenvandenbrandenstift** [comment]
#56
